export const data = {
    en: {
        hourly_forecast: "Hourly Forecast",
        weekly_forecast: "Weekly Forecast",
        uv_index: "uv index",
        wind: "wind",
        sunrise: "sunrise",
        sunset: "Sunset",
        feels_like: "feels like",
        similar_actual_temperature: "Similar to the actual temperature",
        humidity: "humidity",
        dew_point: "The dew point is",
        right_now: "right now",
        visibility: "visibility",
        km: "km",
        pressure: "pressure",
        mmHg: "mmHg",
        setting: "Setting",
        select_language: "Select language",
        weather: "Weather",
        search_city: "Search for a city",
        add_place: "add this place",
        return: "Return",
        loading: "Loading",
    },
    ua: {
        hourly_forecast: "Погодинний прогноз",
        weekly_forecast: "Тижневий прогноз",
        uv_index: "УФ-індекс",
        wind: "вітер",
        sunrise: "схід сонця",
        sunset: "Захід сонця",
        feels_like: "відчув-ся, як",
        similar_actual_temperature: "Подібно до фактичної температури",
        humidity: "вологість",
        dew_point: "Точка роси",
        right_now: "зараз",
        visibility: "видимість",
        km: "км",
        pressure: "тиск",
        mmHg: "мм рт.ст",
        setting: "Налаштування",
        select_language: "Оберіть мову",
        weather: "Погода",
        search_city: "Пошук міста",
        add_place: "добавить это место",
        return: "Вернуться",
        loading: "Загрузка",
    }
}